#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
================================================================================
NVDA 專屬跟單回測腳本
================================================================================
專門針對 NVDA 的回測，支援自訂日期範圍、年度資金注入、信心度分級買入。

功能:
- 回測起始日注入 $2,400，每年第一個交易日再注入 $2,400
- AI 信心度分級買入 (>95%: 25%, 90-95%: 15%, <90%: 不買)
- 市場濾網 (Nasdaq 120MA + DC20 突破)
- 停損停利機制 (-8% / 15%+8%~9%)
- 輸出跟單總結檔案

作者：Phil Liang (Generated by Gemini)
日期：2026-01-18
================================================================================
"""

import os
import sys
import json
import argparse
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime
from tqdm import tqdm

if sys.platform == 'win32':
    sys.stdout.reconfigure(encoding='utf-8')

plt.rcParams['font.sans-serif'] = ['Microsoft JhengHei', 'SimHei', 'Arial Unicode MS']
plt.rcParams['axes.unicode_minus'] = False

from train_us_tech_buy_agent import (
    load_or_update_local_csv,
    calculate_features,
    BENCHMARK, FEATURE_COLS, VAL_RANGE, MODELS_PATH
)

from stable_baselines3 import PPO


# =============================================================================
# 回測參數
# =============================================================================
TICKER = "NVDA"
DEFAULT_START, DEFAULT_END = VAL_RANGE

# 資金注入
YEARLY_INJECTION = 2400

# 信心度門檻與買入比例
CONFIDENCE_HIGH = 0.95      # > 95% → 買入 25%
CONFIDENCE_LOW = 0.90       # 90% - 95% → 買入 15%
BUY_RATIO_HIGH = 0.25       # > 95%
BUY_RATIO_LOW = 0.15        # 90% - 95%

# 風險管理參數
HARD_STOP_PCT = -0.08
TRAILING_ACTIVATION = 0.20
HIGH_PROFIT_THR = 0.25
CALLBACK_BASE = 0.08
CALLBACK_HIGH = 0.17

BASE_OUTPUT_DIR = "backtest_results_nvda"


# =============================================================================
# 模型載入
# =============================================================================
def load_model_manifest(models_path: str) -> dict:
    manifest_path = os.path.join(models_path, "model_manifest.json")
    if not os.path.exists(manifest_path):
        return None
    with open(manifest_path, 'r', encoding='utf-8') as f:
        return json.load(f)


def load_ticker_model(ticker: str, manifest: dict) -> PPO:
    if ticker not in manifest.get("tickers", {}):
        return None
    model_path = manifest["tickers"][ticker]["model_path"]
    if not os.path.exists(model_path):
        return None
    return PPO.load(model_path, device="cpu")


def get_action_confidence(model: PPO, obs: np.ndarray) -> tuple:
    obs_tensor = torch.as_tensor(obs.reshape(1, -1), dtype=torch.float32)
    with torch.no_grad():
        distribution = model.policy.get_distribution(obs_tensor)
        probs = distribution.distribution.probs.numpy()[0]
        action, _ = model.predict(obs, deterministic=True)
        return int(action), float(probs[1])


# =============================================================================
# 市場濾網計算
# =============================================================================
def prepare_market_filter(benchmark_df: pd.DataFrame, ticker_df: pd.DataFrame) -> pd.DataFrame:
    """計算市場濾網指標"""
    # Nasdaq 120MA
    benchmark_df = benchmark_df.copy()
    benchmark_df['Nasdaq_120MA'] = benchmark_df['Close'].rolling(120).mean()
    benchmark_df['Nasdaq_Above_120MA'] = benchmark_df['Close'] > benchmark_df['Nasdaq_120MA']
    
    # 個股 20 日唐其安通道
    ticker_df = ticker_df.copy()
    ticker_df['DC20_High'] = ticker_df['High'].rolling(20).max().shift(1)
    ticker_df['Ticker_Above_DC20'] = ticker_df['Close'] > ticker_df['DC20_High']
    
    # 合併 Nasdaq 指標到個股資料
    nasdaq_cols = ['Nasdaq_120MA', 'Nasdaq_Above_120MA']
    for col in nasdaq_cols:
        ticker_df[col] = benchmark_df[col].reindex(ticker_df.index).ffill()
    
    # 添加 Nasdaq Close
    ticker_df['Nasdaq_Close'] = benchmark_df['Close'].reindex(ticker_df.index).ffill()
    
    return ticker_df


def check_entry_condition(row: pd.Series) -> tuple:
    """檢查進場條件"""
    nasdaq_above_ma = row.get('Nasdaq_Above_120MA', False)
    ticker_above_dc = row.get('Ticker_Above_DC20', False)
    
    if nasdaq_above_ma:
        return True, "bull_market"
    
    if not nasdaq_above_ma and ticker_above_dc:
        return True, "breakout"
    
    return False, "blocked"


# =============================================================================
# 回測引擎
# =============================================================================
class NVDAFollowBacktester:
    """NVDA 跟單回測器"""
    
    def __init__(self, yearly_injection: float = YEARLY_INJECTION):
        self.yearly_injection = yearly_injection
        self.capital_pool = 0.0  # 資金池
        self.positions = []      # 持倉列表
        self.trades = []         # 交易紀錄
        self.equity_curve = []   # 淨值曲線
        self.injection_log = []  # 注入紀錄
        self.buy_signals = []    # 買入訊號
        self.sell_signals = []   # 賣出訊號
        self.blocked_signals = []  # 被濾網擋住的訊號
    
    def run(self, model: PPO, features_df: pd.DataFrame, 
            benchmark_df: pd.DataFrame, start_date: str, end_date: str) -> dict:
        """執行回測"""
        # 準備市場濾網
        test_df = prepare_market_filter(benchmark_df, features_df)
        
        # 過濾測試期間
        test_df = test_df[
            (test_df.index >= pd.Timestamp(start_date)) &
            (test_df.index <= pd.Timestamp(end_date))
        ].copy()
        
        if len(test_df) == 0:
            return None
        
        dates = test_df.index.tolist()
        closes = test_df['Close'].values
        features = test_df[FEATURE_COLS].values.astype(np.float32)
        
        # 初始化: 起始日注入資金
        self.capital_pool = self.yearly_injection
        self.injection_log.append({'date': dates[0], 'amount': self.yearly_injection, 'type': 'initial'})
        
        current_year = dates[0].year
        year_first_day_processed = {current_year: True}  # 起始年已處理
        
        for i in tqdm(range(len(test_df)), desc=f"  Backtesting {TICKER}", leave=False):
            date = dates[i]
            price = closes[i]
            row = test_df.iloc[i]
            
            # =====================================================================
            # 每年第一個交易日注入資金
            # =====================================================================
            if date.year != current_year:
                current_year = date.year
                if current_year not in year_first_day_processed:
                    self.capital_pool += self.yearly_injection
                    self.injection_log.append({
                        'date': date, 
                        'amount': self.yearly_injection, 
                        'type': 'yearly'
                    })
                    year_first_day_processed[current_year] = True
            
            # =====================================================================
            # 計算當前淨值
            # =====================================================================
            position_value = sum(p['shares'] * price for p in self.positions)
            current_value = self.capital_pool + position_value
            self.equity_curve.append({
                'date': date, 
                'value': current_value,
                'capital_pool': self.capital_pool,
                'position_value': position_value
            })
            
            # =====================================================================
            # 持倉管理: 檢查出場條件
            # =====================================================================
            positions_to_remove = []
            for idx, pos in enumerate(self.positions):
                buy_price = pos['buy_price']
                current_return = price / buy_price - 1
                highest_return = pos['highest_price'] / buy_price - 1
                drawdown_from_high = (pos['highest_price'] - price) / pos['highest_price']
                
                # 更新最高價
                if price > pos['highest_price']:
                    pos['highest_price'] = price
                
                sell_reason = None
                
                # 硬性停損
                if current_return <= HARD_STOP_PCT:
                    sell_reason = "Hard Stop"
                # 移動停利
                elif highest_return >= TRAILING_ACTIVATION:
                    cb_limit = CALLBACK_HIGH if highest_return >= HIGH_PROFIT_THR else CALLBACK_BASE
                    if drawdown_from_high >= cb_limit:
                        sell_reason = "Trailing Stop"
                
                if sell_reason:
                    sell_value = pos['shares'] * price
                    profit = sell_value - pos['cost']
                    self.capital_pool += sell_value  # 資金回流
                    
                    self.trades.append({
                        'buy_date': pos['buy_date'],
                        'buy_price': buy_price,
                        'sell_date': date,
                        'sell_price': price,
                        'shares': pos['shares'],
                        'cost': pos['cost'],
                        'sell_value': sell_value,
                        'return': current_return,
                        'profit': profit,
                        'hold_days': (date - pos['buy_date']).days,
                        'exit_reason': sell_reason,
                        'entry_type': pos['entry_type'],
                        'confidence': pos['confidence']
                    })
                    self.sell_signals.append((date, price, sell_reason))
                    positions_to_remove.append(idx)
            
            # 移除已平倉的部位
            for idx in sorted(positions_to_remove, reverse=True):
                self.positions.pop(idx)
            
            # =====================================================================
            # 進場: 檢查 AI 買入信號
            # =====================================================================
            obs = features[i]
            action, confidence = get_action_confidence(model, obs)
            
            if action == 1:  # Agent 發出買入信號
                # 檢查市場濾網
                allow_entry, entry_type = check_entry_condition(row)
                
                if allow_entry:
                    # 根據信心度決定買入比例
                    if confidence > CONFIDENCE_HIGH:
                        buy_ratio = BUY_RATIO_HIGH
                    elif confidence >= CONFIDENCE_LOW:
                        buy_ratio = BUY_RATIO_LOW
                    else:
                        buy_ratio = 0  # 不買入
                    
                    if buy_ratio > 0 and self.capital_pool > 0:
                        invest_amount = self.capital_pool * buy_ratio
                        
                        # 跳過無法買到1股的情況 (避免產生無意義的倉位)
                        if invest_amount < price:
                            continue
                        
                        shares = invest_amount / price  # 允許小數股
                        
                        if shares > 0:
                            cost = shares * price
                            self.capital_pool -= cost
                            
                            self.positions.append({
                                'shares': shares,
                                'buy_price': price,
                                'buy_date': date,
                                'cost': cost,
                                'highest_price': price,
                                'confidence': confidence,
                                'entry_type': entry_type
                            })
                            self.buy_signals.append((date, price, entry_type, confidence, buy_ratio))
                    elif confidence < CONFIDENCE_LOW:
                        self.blocked_signals.append((date, price, confidence, 'low_confidence'))
                else:
                    self.blocked_signals.append((date, price, confidence, 'filter_blocked'))
        
        # 回測結束時的最後狀態
        final_date = dates[-1]
        final_price = closes[-1]
        final_row = test_df.iloc[-1]
        
        return self._generate_results(test_df, final_date, final_price, final_row, model, features[-1])
    
    def _generate_results(self, test_df: pd.DataFrame, final_date, final_price, final_row, model, final_obs) -> dict:
        """生成回測結果"""
        if not self.equity_curve:
            return None
        
        equity_df = pd.DataFrame(self.equity_curve)
        equity_df['date'] = pd.to_datetime(equity_df['date'])
        equity_df.set_index('date', inplace=True)
        
        # 計算總注入金額
        total_injected = sum(log['amount'] for log in self.injection_log)
        
        # 最終淨值
        position_value = sum(p['shares'] * final_price for p in self.positions)
        final_value = self.capital_pool + position_value
        total_return = (final_value - total_injected) / total_injected
        
        # 計算年化報酬
        days = (equity_df.index[-1] - equity_df.index[0]).days
        years = days / 365.0
        cagr = (final_value / total_injected) ** (1 / years) - 1 if years > 0 else 0
        
        # Sharpe Ratio
        daily_returns = equity_df['value'].pct_change().dropna()
        if len(daily_returns) > 0 and daily_returns.std() > 0:
            sharpe = (daily_returns.mean() * 252 - 0.02) / (daily_returns.std() * np.sqrt(252))
        else:
            sharpe = 0
        
        # Maximum Drawdown
        rolling_max = equity_df['value'].cummax()
        drawdown = (equity_df['value'] - rolling_max) / rolling_max
        max_drawdown = drawdown.min()
        
        # 勝率
        if self.trades:
            wins = sum(1 for t in self.trades if t['return'] > 0)
            win_rate = wins / len(self.trades)
        else:
            win_rate = 0
        
        # 獲取最後一天的 AI 信號
        final_action, final_confidence = get_action_confidence(model, final_obs)
        allow_entry, entry_type = check_entry_condition(final_row)
        
        return {
            'ticker': TICKER,
            'total_injected': total_injected,
            'final_value': final_value,
            'capital_pool': self.capital_pool,
            'position_value': position_value,
            'total_return': total_return,
            'cagr': cagr,
            'sharpe_ratio': sharpe,
            'max_drawdown': max_drawdown,
            'total_trades': len(self.trades),
            'win_rate': win_rate,
            'injection_count': len(self.injection_log),
            'equity_df': equity_df,
            'positions': self.positions.copy(),
            'trades': self.trades.copy(),
            'buy_signals': self.buy_signals.copy(),
            'sell_signals': self.sell_signals.copy(),
            'blocked_signals': self.blocked_signals.copy(),
            'injection_log': self.injection_log.copy(),
            'test_start': test_df.index[0],
            'test_end': test_df.index[-1],
            'final_date': final_date,
            'final_price': final_price,
            'final_row': final_row,
            'final_action': final_action,
            'final_confidence': final_confidence,
            'final_allow_entry': allow_entry,
            'final_entry_type': entry_type
        }


# =============================================================================
# Benchmark: Nasdaq Buy & Hold (同等資金注入)
# =============================================================================
def calculate_nasdaq_benchmark(benchmark_df: pd.DataFrame, start_date: str, end_date: str) -> dict:
    """計算 Nasdaq 買入持有的基準 (同等年度資金注入)"""
    test_df = benchmark_df[
        (benchmark_df.index >= pd.Timestamp(start_date)) &
        (benchmark_df.index <= pd.Timestamp(end_date))
    ].copy()
    
    if len(test_df) == 0:
        return None
    
    dates = test_df.index.tolist()
    closes = test_df['Close'].values
    
    # 同樣的資金注入邏輯
    total_shares = 0.0
    total_invested = 0.0
    equity_curve = []
    
    current_year = dates[0].year
    year_first_day_processed = {current_year: True}
    
    # 初始注入
    initial_price = closes[0]
    initial_shares = YEARLY_INJECTION / initial_price
    total_shares += initial_shares
    total_invested += YEARLY_INJECTION
    
    for i, (date, price) in enumerate(zip(dates, closes)):
        # 每年第一個交易日注入
        if date.year != current_year:
            current_year = date.year
            if current_year not in year_first_day_processed:
                new_shares = YEARLY_INJECTION / price
                total_shares += new_shares
                total_invested += YEARLY_INJECTION
                year_first_day_processed[current_year] = True
        
        current_value = total_shares * price
        equity_curve.append({'date': date, 'value': current_value})
    
    equity_df = pd.DataFrame(equity_curve)
    equity_df['date'] = pd.to_datetime(equity_df['date'])
    equity_df.set_index('date', inplace=True)
    
    final_value = total_shares * closes[-1]
    total_return = (final_value - total_invested) / total_invested
    
    days = (dates[-1] - dates[0]).days
    years = days / 365.0
    cagr = (final_value / total_invested) ** (1 / years) - 1 if years > 0 else 0
    
    daily_returns = equity_df['value'].pct_change().dropna()
    if len(daily_returns) > 0 and daily_returns.std() > 0:
        sharpe = (daily_returns.mean() * 252 - 0.02) / (daily_returns.std() * np.sqrt(252))
    else:
        sharpe = 0
    
    rolling_max = equity_df['value'].cummax()
    drawdown = (equity_df['value'] - rolling_max) / rolling_max
    max_drawdown = drawdown.min()
    
    return {
        'ticker': '^IXIC (Nasdaq B&H)',
        'total_invested': total_invested,
        'final_value': final_value,
        'total_return': total_return,
        'cagr': cagr,
        'sharpe_ratio': sharpe,
        'max_drawdown': max_drawdown,
        'equity_df': equity_df
    }


# =============================================================================
# 輸出: End Date Summary
# =============================================================================
def generate_end_date_summary(result: dict, benchmark: dict, output_dir: str, 
                               start_date: str, end_date: str):
    """生成回測最後一天的跟單總結"""
    start_short = start_date.replace('-', '')
    end_short = end_date.replace('-', '')
    filename = f"end_date_summary_NVDA_{start_short}_{end_short}.txt"
    filepath = os.path.join(output_dir, filename)
    
    final_date = result['final_date']
    final_price = result['final_price']
    final_row = result['final_row']
    positions = result['positions']
    capital_pool = result['capital_pool']
    
    lines = []
    lines.append("=" * 60)
    lines.append(f"📅 報告日期: {final_date.strftime('%Y-%m-%d')}")
    lines.append("=" * 60)
    
    # 市場數據
    lines.append("[市場數據 - NVDA]")
    lines.append(f"📊 Close: ${final_price:.2f}")
    lines.append("-" * 30)
    lines.append("[市場數據 - Nasdaq]")
    lines.append(f"📊 Close: {final_row.get('Nasdaq_Close', 'N/A'):.2f}")
    lines.append(f"   120MA: {final_row.get('Nasdaq_120MA', 'N/A'):.2f}")
    lines.append(f"   Close > 120MA: {'✅ YES' if final_row.get('Nasdaq_Above_120MA', False) else '❌ NO'}")
    lines.append("-" * 30)
    
    # 濾網與 AI 信號
    lines.append("[濾網與 AI 信號]")
    allow_entry = result['final_allow_entry']
    entry_type = result['final_entry_type']
    action = result['final_action']
    confidence = result['final_confidence']
    
    action_str = "BUY" if action == 1 else "WAIT"
    lines.append(f"   🤖 AI Action: {action_str} (Conf: {confidence*100:.1f}%)")
    lines.append(f"   📊 進場允許: {'✅ YES' if allow_entry else '❌ NO'} ({entry_type})")
    lines.append("-" * 50)
    
    # 帳戶狀態
    position_value = sum(p['shares'] * final_price for p in positions)
    total_value = capital_pool + position_value
    total_injected = result['total_injected']
    unrealized_pnl = position_value - sum(p['cost'] for p in positions) if positions else 0
    unrealized_pct = unrealized_pnl / sum(p['cost'] for p in positions) * 100 if positions else 0
    
    lines.append("[帳戶狀態]")
    lines.append(f"   💵 資金池餘額 (Cash):  ${capital_pool:,.2f}")
    lines.append(f"   💎 持倉市值 (Value):   ${position_value:,.2f}")
    lines.append(f"   🏦 總資產 (Total):     ${total_value:,.2f}")
    lines.append(f"   📈 未實現損益:         ${unrealized_pnl:,.2f} ({unrealized_pct:+.2f}%)")
    lines.append(f"   💰 累計注入:           ${total_injected:,.2f}")
    lines.append(f"   📊 總報酬率:           {result['total_return']*100:+.2f}%")
    lines.append("-" * 50)
    
    # 持倉明細
    lines.append(f"[持倉明細] (共 {len(positions)} 倉)")
    for idx, pos in enumerate(positions, 1):
        buy_date = pos['buy_date'].strftime('%Y-%m-%d')
        buy_price = pos['buy_price']
        cost = pos['cost']
        shares = pos['shares']
        current_value = shares * final_price
        ret = (final_price / buy_price - 1) * 100
        highest = pos['highest_price']
        conf = pos['confidence']
        
        lines.append(f"   #{idx} 買入: {buy_date} @ ${buy_price:.2f} (信心: {conf*100:.1f}%)")
        lines.append(f"       股數: {shares:.4f} | 成本: ${cost:,.2f} | 市值: ${current_value:,.2f}")
        lines.append(f"       報酬: {ret:+.2f}% | 最高價: ${highest:.2f}")
        
        # 停損停利價位
        hard_stop_price = buy_price * (1 + HARD_STOP_PCT)
        trailing_trigger_price = buy_price * (1 + TRAILING_ACTIVATION)
        lines.append(f"       🛑 硬性停損: ${hard_stop_price:.2f}")
        
        highest_return = highest / buy_price - 1
        if highest_return >= TRAILING_ACTIVATION:
            cb_limit = CALLBACK_HIGH if highest_return >= HIGH_PROFIT_THR else CALLBACK_BASE
            trailing_stop_price = highest * (1 - cb_limit)
            lines.append(f"       📉 移動停利: ${trailing_stop_price:.2f} (回檔 {cb_limit*100:.0f}%)")
        else:
            lines.append(f"       📉 移動停利: (未啟動, 需漲至 ${trailing_trigger_price:.2f})")
        lines.append("")
    
    lines.append("-" * 50)
    
    # 明日交易建議
    lines.append("[🔮 明日交易建議 - 開盤執行]")
    lines.append("")
    
    # 買入建議
    if action == 1 and allow_entry:
        if confidence > CONFIDENCE_HIGH:
            buy_ratio = BUY_RATIO_HIGH
            ratio_desc = ">95%"
        elif confidence >= CONFIDENCE_LOW:
            buy_ratio = BUY_RATIO_LOW
            ratio_desc = "90%-95%"
        else:
            buy_ratio = 0
            ratio_desc = "<90%"
        
        if buy_ratio > 0 and capital_pool > 0:
            buy_amount = capital_pool * buy_ratio
            lines.append(f"   📈 【買入建議】: ✅ 建議買入")
            lines.append(f"      💰 建議買入金額: ${buy_amount:,.2f}")
            lines.append(f"      📊 資金比例: {buy_ratio*100:.0f}% (AI 信心度 {ratio_desc})")
            lines.append(f"      💵 資金池餘額: ${capital_pool:,.2f}")
        else:
            lines.append(f"   📈 【買入建議】: ❌ 不建議買入")
            lines.append(f"      ⚠️ 原因: 信心度不足 ({confidence*100:.1f}% < 90%)")
    else:
        lines.append(f"   📈 【買入建議】: ❌ 不建議買入")
        if action != 1:
            lines.append(f"      ⚠️ 原因: AI 未發出買入信號")
        elif not allow_entry:
            lines.append(f"      ⚠️ 原因: 市場濾網阻擋 ({entry_type})")
    
    lines.append("")
    lines.append("-" * 30)
    lines.append("")
    
    # 賣出監控
    lines.append("   📉 【賣出監控】: 停損/停利觸發價位")
    lines.append("")
    for idx, pos in enumerate(positions, 1):
        buy_price = pos['buy_price']
        shares = pos['shares']
        current_value = shares * final_price
        highest = pos['highest_price']
        
        hard_stop_price = buy_price * (1 + HARD_STOP_PCT)
        hard_stop_value = shares * hard_stop_price
        
        lines.append(f"      #倉{idx} (市值 ${current_value:,.2f}):")
        lines.append(f"         🛑 硬停損觸發: NVDA 跌至 ${hard_stop_price:.2f} 時賣出")
        lines.append(f"            → 預計收回: ${hard_stop_value:,.2f}")
        
        highest_return = highest / buy_price - 1
        if highest_return >= TRAILING_ACTIVATION:
            cb_limit = CALLBACK_HIGH if highest_return >= HIGH_PROFIT_THR else CALLBACK_BASE
            trailing_stop_price = highest * (1 - cb_limit)
            trailing_value = shares * trailing_stop_price
            lines.append(f"         📉 移動停利: NVDA 跌至 ${trailing_stop_price:.2f} 時賣出")
            lines.append(f"            → 預計收回: ${trailing_value:,.2f}")
        else:
            lines.append(f"         📉 移動停利: 未啟動 (需漲 {TRAILING_ACTIVATION*100:.0f}%)")
        lines.append("")
    
    lines.append("=" * 60)
    lines.append("📊 績效摘要")
    lines.append("=" * 60)
    lines.append(f"   策略 (NVDA AI Follow):")
    lines.append(f"      總報酬: {result['total_return']*100:+.2f}%")
    lines.append(f"      CAGR: {result['cagr']*100:.2f}%")
    lines.append(f"      Sharpe: {result['sharpe_ratio']:.2f}")
    lines.append(f"      MDD: {result['max_drawdown']*100:.2f}%")
    lines.append(f"      交易次數: {result['total_trades']}")
    lines.append(f"      勝率: {result['win_rate']*100:.1f}%")
    lines.append("")
    
    if benchmark:
        lines.append(f"   基準 (Nasdaq B&H):")
        lines.append(f"      總報酬: {benchmark['total_return']*100:+.2f}%")
        lines.append(f"      CAGR: {benchmark['cagr']*100:.2f}%")
        lines.append(f"      Sharpe: {benchmark['sharpe_ratio']:.2f}")
        lines.append(f"      MDD: {benchmark['max_drawdown']*100:.2f}%")
    
    lines.append("=" * 60)
    
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))
    
    print(f"✅ 跟單總結已儲存: {filepath}")
    return filepath


# =============================================================================
# 視覺化
# =============================================================================
def plot_equity_curve(result: dict, benchmark: dict, output_dir: str,
                      start_date: str, end_date: str):
    """繪製淨值曲線"""
    fig, ax = plt.subplots(figsize=(14, 8))
    
    # 策略淨值
    equity_df = result['equity_df']
    ax.plot(equity_df.index, equity_df['value'], 
            label=f"NVDA AI Follow ({result['total_return']:.0%})",
            linewidth=2, color='#4CAF50')
    
    # Benchmark
    if benchmark:
        bench_equity = benchmark['equity_df']
        ax.plot(bench_equity.index, bench_equity['value'],
                label=f"Nasdaq B&H ({benchmark['total_return']:.0%})",
                linewidth=2, linestyle='--', color='gray')
    
    # 資金注入標記
    for log in result['injection_log']:
        ax.axvline(x=log['date'], color='blue', linestyle=':', alpha=0.5)
    
    # 買入訊號
    if result['buy_signals']:
        buy_dates = [s[0] for s in result['buy_signals']]
        # 找到對應的 equity 值
        buy_values = [equity_df.loc[d, 'value'] if d in equity_df.index else None for d in buy_dates]
        valid = [(d, v) for d, v in zip(buy_dates, buy_values) if v is not None]
        if valid:
            dates, values = zip(*valid)
            ax.scatter(dates, values, marker='^', color='green', s=80, zorder=5, label='Buy')
    
    # 賣出訊號
    if result['sell_signals']:
        sell_dates = [s[0] for s in result['sell_signals']]
        sell_values = [equity_df.loc[d, 'value'] if d in equity_df.index else None for d in sell_dates]
        valid = [(d, v) for d, v in zip(sell_dates, sell_values) if v is not None]
        if valid:
            dates, values = zip(*valid)
            ax.scatter(dates, values, marker='v', color='red', s=80, zorder=5, label='Sell')
    
    ax.axhline(y=result['total_injected'], color='black', linestyle=':', alpha=0.3, 
               label=f"Total Injected (${result['total_injected']:,.0f})")
    
    ax.set_title(f'NVDA AI Follow 策略淨值曲線\n{start_date} ~ {end_date}', fontsize=14)
    ax.set_xlabel('Date')
    ax.set_ylabel('Portfolio Value ($)')
    ax.legend(loc='upper left', fontsize=10)
    ax.grid(True, alpha=0.3)
    ax.set_ylim(bottom=0)
    
    plt.tight_layout()
    chart_path = os.path.join(output_dir, "equity_curve_nvda_follow.png")
    plt.savefig(chart_path, dpi=150, bbox_inches='tight')
    plt.close()
    print(f"✅ 淨值曲線已儲存: {chart_path}")


def save_trade_log(result: dict, output_dir: str, start_date: str, end_date: str):
    """儲存交易紀錄"""
    if not result['trades']:
        print("⚠️ 無交易紀錄")
        return
    
    trades_df = pd.DataFrame(result['trades'])
    start_short = start_date.replace('-', '')
    end_short = end_date.replace('-', '')
    filename = f"trade_log_NVDA_{start_short}_{end_short}.csv"
    filepath = os.path.join(output_dir, filename)
    trades_df.to_csv(filepath, index=False, encoding='utf-8-sig')
    print(f"✅ 交易紀錄已儲存: {filepath}")


# =============================================================================
# 命令列參數
# =============================================================================
def parse_args():
    parser = argparse.ArgumentParser(description='NVDA 專屬跟單回測腳本')
    parser.add_argument('--start', type=str, default=DEFAULT_START,
                        help=f'回測起始日期 (預設: {DEFAULT_START})')
    parser.add_argument('--end', type=str, default=DEFAULT_END,
                        help=f'回測結束日期 (預設: {DEFAULT_END})')
    return parser.parse_args()


# =============================================================================
# 主程式
# =============================================================================
def main():
    args = parse_args()
    start_date = args.start
    end_date = args.end
    
    # 日期驗證：如果起始日晚於結束日，將結束日設為今天
    if pd.Timestamp(start_date) > pd.Timestamp(end_date):
        end_date = datetime.now().strftime('%Y-%m-%d')
        print(f"⚠️  起始日晚於預設結束日，自動將結束日設為今天: {end_date}")
    
    # 動態輸出目錄 (放在專屬目錄內，按日期區分)
    start_short = start_date.replace('-', '')
    end_short = end_date.replace('-', '')
    output_dir = os.path.join(BASE_OUTPUT_DIR, f"{start_short}_{end_short}")
    
    print("=" * 70)
    print("  NVDA 專屬跟單回測")
    print(f"  期間: {start_date} ~ {end_date}")
    print(f"  資金注入: ${YEARLY_INJECTION:,}/年")
    print(f"  信心度門檻: >{CONFIDENCE_HIGH*100:.0f}%→{BUY_RATIO_HIGH*100:.0f}%, "
          f"{CONFIDENCE_LOW*100:.0f}%-{CONFIDENCE_HIGH*100:.0f}%→{BUY_RATIO_LOW*100:.0f}%")
    print(f"  輸出: {output_dir}/")
    print("=" * 70)
    
    os.makedirs(output_dir, exist_ok=True)
    
    # 載入模型
    print("\n[Step 1] 載入模型...")
    manifest = load_model_manifest(MODELS_PATH)
    if manifest is None:
        print("❌ 無法載入 manifest")
        return
    
    model = load_ticker_model(TICKER, manifest)
    if model is None:
        print(f"❌ 無法載入 {TICKER} 模型")
        return
    print(f"✅ {TICKER} 模型載入成功")
    
    # 載入數據
    print("\n[Step 2] 載入數據...")
    benchmark_df = load_or_update_local_csv(BENCHMARK)
    if benchmark_df is None:
        print("❌ 無法載入基準指數")
        return
    
    raw_df = load_or_update_local_csv(TICKER)
    if raw_df is None:
        print(f"❌ 無法載入 {TICKER} 數據")
        return
    
    features_df = calculate_features(raw_df, benchmark_df, TICKER, use_cache=True)
    print(f"✅ 數據載入完成")
    
    # 計算 Benchmark
    print("\n[Step 3] 計算 Nasdaq Benchmark...")
    benchmark = calculate_nasdaq_benchmark(benchmark_df, start_date, end_date)
    if benchmark:
        print(f"   Nasdaq B&H: Return={benchmark['total_return']:.1%} | CAGR={benchmark['cagr']:.1%}")
    
    # 執行回測
    print("\n[Step 4] 執行回測...")
    backtester = NVDAFollowBacktester(YEARLY_INJECTION)
    result = backtester.run(model, features_df, benchmark_df, start_date, end_date)
    
    if result is None:
        print("❌ 回測失敗")
        return
    
    # 輸出結果
    print("\n[Step 5] 輸出結果...")
    
    print("\n" + "=" * 70)
    print("📊 回測績效")
    print("=" * 70)
    print(f"   {'指標':<20} | {'NVDA AI Follow':<20} | {'Nasdaq B&H':<20}")
    print("-" * 70)
    print(f"   {'總報酬':<20} | {result['total_return']:>18.1%} | {benchmark['total_return'] if benchmark else 'N/A':>18.1%}")
    print(f"   {'CAGR':<20} | {result['cagr']:>18.1%} | {benchmark['cagr'] if benchmark else 'N/A':>18.1%}")
    print(f"   {'Sharpe Ratio':<20} | {result['sharpe_ratio']:>18.2f} | {benchmark['sharpe_ratio'] if benchmark else 'N/A':>18.2f}")
    print(f"   {'Max Drawdown':<20} | {result['max_drawdown']:>18.1%} | {benchmark['max_drawdown'] if benchmark else 'N/A':>18.1%}")
    print(f"   {'交易次數':<20} | {result['total_trades']:>18} | {'N/A':>18}")
    print(f"   {'勝率':<20} | {result['win_rate']:>18.1%} | {'N/A':>18}")
    print("=" * 70)
    
    generate_end_date_summary(result, benchmark, output_dir, start_date, end_date)
    plot_equity_curve(result, benchmark, output_dir, start_date, end_date)
    save_trade_log(result, output_dir, start_date, end_date)
    
    print("\n" + "=" * 70)
    print("  ✅ 回測完成！")
    print(f"  📁 結果儲存於: {output_dir}/")
    print("=" * 70)


if __name__ == "__main__":
    main()
